// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/ijufumi/email-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SendMailService is an autogenerated mock type for the SendMailService type
type SendMailService struct {
	mock.Mock
}

// Send provides a mock function with given fields: contents
func (_m *SendMailService) Send(contents model.SendMailRequest) error {
	ret := _m.Called(contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SendMailRequest) error); ok {
		r0 = rf(contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSendMailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewSendMailService creates a new instance of SendMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendMailService(t mockConstructorTestingTNewSendMailService) *SendMailService {
	mock := &SendMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
