// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/ijufumi/email-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SendMailVendor is an autogenerated mock type for the SendMailVendor type
type SendMailVendor struct {
	mock.Mock
}

// Send provides a mock function with given fields: contents
func (_m *SendMailVendor) Send(contents model.SendMailRequest) error {
	ret := _m.Called(contents)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SendMailRequest) error); ok {
		r0 = rf(contents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSendMailVendor interface {
	mock.TestingT
	Cleanup(func())
}

// NewSendMailVendor creates a new instance of SendMailVendor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendMailVendor(t mockConstructorTestingTNewSendMailVendor) *SendMailVendor {
	mock := &SendMailVendor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
