// Code generated by mockery. DO NOT EDIT.

package stubs

import (
	context "context"

	sesv2 "github.com/aws/aws-sdk-go-v2/service/sesv2"
	mock "github.com/stretchr/testify/mock"
)

// ListCustomVerificationEmailTemplatesAPIClient is an autogenerated mock type for the ListCustomVerificationEmailTemplatesAPIClient type
type ListCustomVerificationEmailTemplatesAPIClient struct {
	mock.Mock
}

// ListCustomVerificationEmailTemplates provides a mock function with given fields: _a0, _a1, _a2
func (_m *ListCustomVerificationEmailTemplatesAPIClient) ListCustomVerificationEmailTemplates(_a0 context.Context, _a1 *sesv2.ListCustomVerificationEmailTemplatesInput, _a2 ...func(*sesv2.Options)) (*sesv2.ListCustomVerificationEmailTemplatesOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *sesv2.ListCustomVerificationEmailTemplatesOutput
	if rf, ok := ret.Get(0).(func(context.Context, *sesv2.ListCustomVerificationEmailTemplatesInput, ...func(*sesv2.Options)) *sesv2.ListCustomVerificationEmailTemplatesOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sesv2.ListCustomVerificationEmailTemplatesOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sesv2.ListCustomVerificationEmailTemplatesInput, ...func(*sesv2.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewListCustomVerificationEmailTemplatesAPIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewListCustomVerificationEmailTemplatesAPIClient creates a new instance of ListCustomVerificationEmailTemplatesAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewListCustomVerificationEmailTemplatesAPIClient(t mockConstructorTestingTNewListCustomVerificationEmailTemplatesAPIClient) *ListCustomVerificationEmailTemplatesAPIClient {
	mock := &ListCustomVerificationEmailTemplatesAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
